--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

-- Started on 2025-06-21 12:23:09

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 133980)
-- Name: carritos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.carritos (
    id bigint NOT NULL,
    usuarioid uuid
);


ALTER TABLE public.carritos OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 133979)
-- Name: carritos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.carritos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carritos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 133986)
-- Name: cartitems; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cartitems (
    id bigint NOT NULL,
    cantidad integer NOT NULL,
    cartid bigint,
    productoid bigint
);


ALTER TABLE public.cartitems OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 133985)
-- Name: cartitems_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cartitems ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cartitems_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 133992)
-- Name: detalles_pedido; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.detalles_pedido (
    id bigint NOT NULL,
    cantidad integer NOT NULL,
    nombre_producto character varying(255),
    historialid uuid
);


ALTER TABLE public.detalles_pedido OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 133991)
-- Name: detalles_pedido_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.detalles_pedido ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalles_pedido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 133998)
-- Name: historial; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.historial (
    id bigint NOT NULL,
    fecha date,
    usuarioid uuid
);


ALTER TABLE public.historial OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 133997)
-- Name: historial_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.historial ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.historial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 134013)
-- Name: producto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.producto (
    id bigint NOT NULL,
    categoria character varying(255),
    descripcion character varying(255),
    imagenurl character varying(255),
    nombre character varying(255),
    disponibilidad boolean DEFAULT true,
    CONSTRAINT producto_categoria_check CHECK (((categoria)::text = ANY ((ARRAY['Ficción'::character varying, 'No Ficción'::character varying, 'Ciencia Ficción'::character varying, 'Fantasía'::character varying, 'Misterio'::character varying, 'Romance'::character varying, 'Terror'::character varying, 'Biografía'::character varying, 'Historia'::character varying, 'Infantil'::character varying, 'Poesía'::character varying, 'Drama'::character varying])::text[])))
);


ALTER TABLE public.producto OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 134012)
-- Name: producto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.producto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.producto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 134022)
-- Name: usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios (
    id uuid NOT NULL DEFAULT gen_random_uuid(), 
    nombre character varying(255),
    apellido character varying(255),
    cedula character varying(255),
    email character varying(255),
    pass character varying(255),
    rol character varying(255),
    telefono character varying(255),
    usuario character varying(255),
    CONSTRAINT usuarios_rol_check CHECK (((rol)::text = ANY ((ARRAY['ADMIN'::character varying, 'USER'::character varying])::text[])))
);


ALTER TABLE public.usuarios OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 134021)
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



--
-- TOC entry 4895 (class 0 OID 133986)
-- Dependencies: 218
-- Data for Name: cartitems; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cartitems (id, cantidad, cartid, productoid) FROM stdin;
\.


--
-- TOC entry 4903 (class 0 OID 134013)
-- Dependencies: 226
-- Data for Name: producto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.producto (id, categoria, descripcion, imagenurl, nombre) FROM stdin;
1	Ficción	Una historia épica de aventuras y magia en un mundo medieval.	https://0.academia-photos.com/attachment_thumbnails/54806472/mini_magick20190115-25903-11tupou.png?1547618110	El Señor de los Anillos
2	Ciencia Ficción	Un viaje interdimensional a través del tiempo y el espacio.	https://images.cdn2.buscalibre.com/fit-in/360x360/0d/73/0d739e6e0e837d7637f97f9aad3639b4.jpg	Dune
3	Fantasía	Una saga de dragones, hechiceros y batallas legendarias.	https://images.cdn2.buscalibre.com/fit-in/360x360/bb/a8/bba87069845f8e2187a469c46ab10d44.jpg	Canción de Hielo y Fuego
\.


SELECT pg_catalog.setval('public.carritos_id_seq', 6, true);


--
-- TOC entry 4912 (class 0 OID 0)
-- Dependencies: 217
-- Name: cartitems_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cartitems_id_seq', 8, true);


--
-- TOC entry 4913 (class 0 OID 0)
-- Dependencies: 219
-- Name: detalles_pedido_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.detalles_pedido_id_seq', 3, true);


--
-- TOC entry 4914 (class 0 OID 0)
-- Dependencies: 221
-- Name: historial_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.historial_id_seq', 3, true);



--
-- TOC entry 4916 (class 0 OID 0)
-- Dependencies: 225
-- Name: producto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.producto_id_seq', 5, true);


--
-- TOC entry 4917 (class 0 OID 0)
-- Dependencies: 227
-- Name: usuarios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuarios_id_seq', 6, true);


--
-- TOC entry 4722 (class 2606 OID 133984)
-- Name: carritos carritos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carritos
    ADD CONSTRAINT carritos_pkey PRIMARY KEY (id);


--
-- TOC entry 4726 (class 2606 OID 133990)
-- Name: cartitems cartitems_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cartitems
    ADD CONSTRAINT cartitems_pkey PRIMARY KEY (id);


--
-- TOC entry 4728 (class 2606 OID 133996)
-- Name: detalles_pedido detalles_pedido_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalles_pedido
    ADD CONSTRAINT detalles_pedido_pkey PRIMARY KEY (id);


--
-- TOC entry 4730 (class 2606 OID 134002)
-- Name: historial historial_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.historial
    ADD CONSTRAINT historial_pkey PRIMARY KEY (id);

--
-- TOC entry 4734 (class 2606 OID 134020)
-- Name: producto producto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT producto_pkey PRIMARY KEY (id);


--
-- TOC entry 4736 (class 2606 OID 134037)
-- Name: usuarios uk3m5n1w5trapxlbo2s42ugwdmd; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT uk3m5n1w5trapxlbo2s42ugwdmd UNIQUE (usuario);


--
-- TOC entry 4738 (class 2606 OID 134033)
-- Name: usuarios ukefovjjo5q5jlsa0f9eoptdjly; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT ukefovjjo5q5jlsa0f9eoptdjly UNIQUE (cedula);


--
-- TOC entry 4740 (class 2606 OID 134035)
-- Name: usuarios ukkfsp0s1tflm1cwlj8idhqsad0; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT ukkfsp0s1tflm1cwlj8idhqsad0 UNIQUE (email);


--
-- TOC entry 4724 (class 2606 OID 134031)
-- Name: carritos ukm4c97aj3t4kcxr4ddyi4a9wo4; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carritos
    ADD CONSTRAINT ukm4c97aj3t4kcxr4ddyi4a9wo4 UNIQUE (usuarioid);


--
-- TOC entry 4742 (class 2606 OID 134029)
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- TOC entry 4743 (class 2606 OID 134038)
-- Name: carritos fk55a2ghxb2tld2604ksxdnri37; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carritos
    ADD CONSTRAINT fk55a2ghxb2tld2604ksxdnri37 FOREIGN KEY (usuarioid) REFERENCES public.usuarios(id);


--
-- TOC entry 4747 (class 2606 OID 134058)
-- Name: historial fk7e0c9k59fdjui4veeevp6rh9e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.historial
    ADD CONSTRAINT fk7e0c9k59fdjui4veeevp6rh9e FOREIGN KEY (usuarioid) REFERENCES public.usuarios(id);


--
-- TOC entry 4744 (class 2606 OID 134048)
-- Name: cartitems fkkj5jbf0e1hvf1pfqc0a2d1tdw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cartitems
    ADD CONSTRAINT fkkj5jbf0e1hvf1pfqc0a2d1tdw FOREIGN KEY (productoid) REFERENCES public.producto(id);


--
-- TOC entry 4746 (class 2606 OID 134053)
-- Name: detalles_pedido fkmvgepabxtnaso9u95cktfganf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalles_pedido
    ADD CONSTRAINT fkmvgepabxtnaso9u95cktfganf FOREIGN KEY (historialid) REFERENCES public.historial(id);


--
-- TOC entry 4745 (class 2606 OID 134043)
-- Name: cartitems fkoo0ndj5hv610rs34b2i7bocvw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cartitems
    ADD CONSTRAINT fkoo0ndj5hv610rs34b2i7bocvw FOREIGN KEY (cartid) REFERENCES public.carritos(id);


-- Completed on 2025-06-21 12:23:09

--
-- PostgreSQL database dump complete
--

