name: CD

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Establecer conexión SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Añadir EC2 a known_hosts
        run: ssh-keyscan -H 18.119.113.12 >> ~/.ssh/known_hosts

      - name: Copiar archivos a la EC2 con rsync
        run: |
          echo "Iniciando transferencia de archivos a EC2..."
          rsync -avz --exclude '.git' ./ ec2-user@18.119.113.12:/home/ec2-user/deploy || {
            echo "Error al copiar archivos con rsync"
            exit 1
          }

      - name: Desplegar en EC2 vía Docker Compose
        run: |
          echo "Ejecutando pasos de despliegue en EC2..."

          ssh ec2-user@18.119.113.12 << 'EOF'
            set -euo pipefail

            echo "Ingresando a la carpeta del proyecto"
            cd /home/ec2-user/deploy

            echo "Limpiando recursos Docker para liberar espacio..."
            docker system prune -af || echo "⚠️o se pudo limpiar Docker"
            docker builder prune -af || echo "⚠️o se pudo limpiar Builder"

            echo "Deteniendo contenedores existentes"
            docker-compose down || echo "No había contenedores activos"

            echo "Construyendo contenedores (build)..."
            export DOCKER_BUILDKIT=1
            docker-compose build --no-cache --progress=plain || {
              echo 'Falló la construcción de contenedores'
              exit 1
            }

            echo "Iniciando contenedores"
            docker-compose up -d || {
              echo 'Falló al iniciar los contenedores'
              exit 1
            }

            echo "Despliegue completado correctamente"
          EOF
