name: CI

on:
  push:
    branches:
      - deploy
  pull_request:
    branches:
      - deploy

jobs:
  build-backend:
    name: Build & Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and test backend with Maven
        run: mvn clean verify --file ./KPCBack/kingdomPC/pom.xml

  build-frontend:
    name: Build & Test Frontend
    runs-on: ubuntu-latest
    needs: build-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./KPCFront/kingdomPC

      - name: Run frontend tests
        run: npm test -- --watchAll=false
        working-directory: ./KPCFront/kingdomPC

      - name: Build frontend production bundle
        run: npm run build
        working-directory: ./KPCFront/kingdomPC
