name: Despliegue Infra

on:
  push:
    branches:
      - deploy

jobs:
  deploy:  
    runs-on: ubuntu-latest

    steps:
      - name: Establecer conexión SSH
        uses: shimataro/ssh-key-action@v2  
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          known_hosts: unnecessary

      - name: Añadir EC2 a known_hosts  
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 22 -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Copiar archivos a la EC2 con rsync
        run: |
          echo "Iniciando transferencia de archivos a EC2..."
          rsync -avz --exclude '.git' ./ ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ec2-user/deploy || {
            echo "Error al copiar archivos con rsync"
            exit 1
          }

      - name: Desplegar BDD y Nginx en EC2 vía Docker Compose
        run: |
          echo "Ejecutando despliegue de BDD y Nginx:"

          ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=10 ec2-user@${{ secrets.EC2_PUBLIC_IP }} << EOF
            set -euo pipefail

            cd /home/ec2-user/BDD_Nginx

            echo "Desplegando BDD y Nginx"
            export DOCKER_BUILDKIT=1
            export POSTGRES_PASSWORD="${POSTGRES_PASSWORD}" 
            
            # REBUILD LIMPIO
            docker-compose build --no-cache
            
            docker-compose up -d || {
              echo 'Falló startup'
              exit 1
            }

            echo "Verificando contenedores"
            docker ps
            echo "Logs de la BDD:"
            docker logs db | tail -20
            echo "Logs de Nginx:"
            docker logs nginx | tail -10

            echo "BDD y Nginx desplegados"
          EOF
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
